"""主题相关常量定义"""

# 主题模式常量
THEME_MODE_AUTO = "auto"
THEME_MODE_LIGHT = "light"
THEME_MODE_DARK = "dark"

# 主题名称常量
THEME_NAME_CLASSIC = "经典"
THEME_NAME_MATERIAL3 = "Material3"

# 主题颜色常量
THEME_COLOR_BLUE = "蓝色"
THEME_COLOR_GREEN = "绿色"
THEME_COLOR_RED = "红色"
THEME_COLOR_PURPLE = "紫色"
THEME_COLOR_ORANGE = "橙色"

# 模式显示名称映射
MODE_DISPLAY_MAP = {
    THEME_MODE_AUTO: "跟随系统",
    THEME_MODE_LIGHT: "浅色",
    THEME_MODE_DARK: "深色"
}

# 反向映射：显示名称到内部值
MODE_DISPLAY_REVERSE_MAP = {
    "跟随系统": THEME_MODE_AUTO,
    "浅色": THEME_MODE_LIGHT,
    "深色": THEME_MODE_DARK
}

# 颜色RGB值映射 (R, G, B)
COLOR_RGB_MAP = {
    THEME_COLOR_BLUE: (50, 150, 250),
    THEME_COLOR_GREEN: (50, 150, 100),
    THEME_COLOR_RED: (200, 50, 50),
    THEME_COLOR_PURPLE: (150, 50, 200),
    THEME_COLOR_ORANGE: (200, 100, 50)
}

# 默认主题配置
DEFAULT_THEME_MODE = THEME_MODE_AUTO
DEFAULT_THEME_NAME = THEME_NAME_CLASSIC
DEFAULT_THEME_COLOR = THEME_COLOR_BLUE